- apt: update-cache=yes cache_valid_time=3600

- import_tasks: packages.yml

- name: Install NGINX configuration
  copy: src=nginx.conf dest=/etc/nginx/ owner=root group=root mode=0644
  notify: restart nginx
  tags: nginx_conf
